llm:
  provider: "gemini"  # gemini | claude | openai

  gemini:
    model: "gemini-pro"
    api_key_env: "GEMINI_API_KEY"
    temperature: 0.5
    max_tokens: 500
    top_p: 0.9
    top_k: 40

  # 향후 확장용 (주석 처리)
  # claude:
  #   model: "claude-3-sonnet-20240229"
  #   api_key_env: "ANTHROPIC_API_KEY"
  #   temperature: 0.5
  #   max_tokens: 500

  # openai:
  #   model: "gpt-4"
  #   api_key_env: "OPENAI_API_KEY"
  #   temperature: 0.5
  #   max_tokens: 500
